### ISSUE TITLE
Enable editing and data loading at certain zoom levels

### ISSUE THREAD

**Issue by drewbo** [developmentseed/skynet-scrub#10]
We should only load GeoJSON features and add them to the `Draw.store` at certain zoom levels to avoid fetching too much data. Related: for which zoom levels should editing be enabled? cc: @dereklieu @kamicut

**Comment by dereklieu** [comment]
Zoom 14 or 15 seem ok to me? The amount of data coming from the ML processing seems to be ok with that zoom level.

**Comment by drewbo** [comment]
Agreed. Let's settle on 15 for now because it's a bit harder to edit in detail further out and this reduces the network load.

**Comment by drewbo** [comment]
Closed via #64
