### ISSUE TITLE
Line join

### ISSUE THREAD

**Issue by dereklieu** [developmentseed/skynet-scrub#12]
By selecting two lines, I should be able to join them into a single one.

**Comment by drewbo** [comment]
For this I'd actually like to try using #13 to continue a line "onto" another one (rather than explicitly having to select join). I think it is a more natural workflow but maybe technically a bit more difficult. Thoughts @dereklieu @felskia @kamicut

**Comment by dereklieu** [comment]
I'd support that. One benefit is, we'd no longer need to calculate which ends of the lines to join.

**Comment by sethvincent** [comment]
Questions about joining lines of different types:

What should the behavior be if a user is trying to join, say, an incomplete line and an in progress line?

My first thought is to make the whole thing "in progress."

I'm not sure what should happen though, if a user tries to join a complete line with a line of a different type (though that seems unlikely maybe?).

**Comment by drewbo** [comment]
@sethvincent good question, let's have it push all affected lines to in-progress

**Comment by dereklieu** [comment]
Done.
