### ISSUE TITLE
Line continuation

### ISSUE THREAD

**Issue by dereklieu** [developmentseed/skynet-scrub#13]
From either end of an existing line, I should be able to continue adding points to the line.

**Comment by drewbo** [comment]
Yup. Functionality started in https://github.com/mapbox/mapbox-gl-draw/pull/606

**Comment by drewbo** [comment]
Merged in `0.17.0`

**Comment by dereklieu** [comment]
💯

**Comment by drewbo** [comment]
Closed via #31, will incorporate in the UI separately
