### ISSUE TITLE
Add grid above base map

### ISSUE THREAD

**Issue by felskia** [developmentseed/skynet-scrub#52]
Add grid to allow users to better chuck off the work they need to do.

**Comment by dereklieu** [comment]
@felskia where should the labels on this grid go?

**Comment by drewbo** [comment]
grid layer (1km and 10km) available at `openroads.32e6fba4`

**Comment by dereklieu** [comment]
@drewbo looks like that's the raster tileset. Do you want me to use that one or `openroads.d9d310da`?

**Comment by drewbo** [comment]
@dereklieu either one, the raster tileset has rendered dotted lines but since we're using gl, feel free to use the vector source directly
