### ISSUE TITLE
Bug: selecting a point, moving the point, then selecting line continuation

### ISSUE THREAD

**Issue by dereklieu** [developmentseed/skynet-scrub#57]
To reproduce:

Click a line
Click a point on that line
Drag the point to move it
Click line continuation UI.

![screen shot 2017-04-24 at 4 58 28 pm](https://cloud.githubusercontent.com/assets/1590802/25346344/45371a48-290f-11e7-9288-e6730aeced8d.png)

**Comment by dereklieu** [comment]
Update: after moving a vertice, while [`draw.getSelected`](https://github.com/developmentseed/skynet-scrub/blob/master/app/scripts/components/map/index.js#L114) returns the updated line, [`draw.getSelectedPoints`](https://github.com/developmentseed/skynet-scrub/blob/master/app/scripts/components/map/index.js#L115) return the old line's coordinates. This fails the continuation since the coordinates are no longer a part of the selected line.

**Comment by dereklieu** [comment]
Upstream issue https://github.com/mapbox/mapbox-gl-draw/issues/632

**Comment by dereklieu** [comment]
This is now fixed upstream but not yet deployed to NPM, as far as I can tell. If we need this fixed sooner we can install from github, otherwise I'm fine keeping this ticket open until the fix is deployed (and we've updated our version).

**Comment by drewbo** [comment]
We can upgrade to `0.18.1` now and close this
